// src/redux/roomOwnerSlice.js
import { createSlice } from '@reduxjs/toolkit';

// Create a slice for roomOwner
const roomOwnerSlice = createSlice({
  name: 'roomOwner',
  initialState: {
    owner: {}, // initial state with no owner
  },
  reducers: {
    // Action to set the room owner
    setRoomOwner: (state, action) => {
      state.owner = action.payload; // set the owner
    },
    // Action to clear the room owner (e.g., when owner leaves)
    clearRoomOwner: (state) => {
      state.owner = {}; // clear the owner
    },
  },
});

// Export the actions generated by the slice
export const { setRoomOwner, clearRoomOwner } = roomOwnerSlice.actions;

// Export the reducer to be included in the store
export default roomOwnerSlice.reducer;
